### ISSUE TITLE
This example can not work

### ISSUE THREAD

**Issue by ramseyfeng** [mdn/fibonacci-worker#2]
1. dump is an FF specific function.
2. fibonacci.js:23 Uncaught ReferenceError: Worker is not defined
    at onmessage (fibonacci.js:23)
onmessage @ fibonacci.js:23

**Comment by zackmorgs** [comment]
yeah i guess im not seeing it work on my browser at least.

**Comment by chrisdavidmills** [comment]
Thanks for bringing this up. I've tried rewriting it to simplify the code, and I've run into a weird problem — it works fine on my local copy, but the live version on gh-pages doesn't work properly.

Any thoughts? ;-)

**Comment by chrisdavidmills** [comment]
Ah, wait. On Chrome it seems to work fine, but on Firefox is goes all kinds of weird. Better file a bug I guess ;-)

**Comment by zackmorgs** [comment]
Hey man, i'm seeing it work now so I think you fixed whatever it was.

**Comment by chrisdavidmills** [comment]
Cool! We'll close the issue then.
